name: Generate requirements.txt

on:
  push:
    branches:
      - main  # 您可以根據需要更改分支名稱

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # 替換為您需要的 Python 版本

    - name: Install pipreqs
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs

    - name: Generate requirements.txt
      run: |
        pipreqs ./GameCorner --force

    - name: Check if requirements.txt exists
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt not found, creating an empty one."
          touch requirements.txt
        fi

    - name: Add requirements.txt to Git tracking
      run: |
        git add requirements.txt

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m 'Auto-generate requirements.txt' || echo "No changes to commit"
        git push
