name: Generate requirements.txt

on:
  push:
    branches:
      - main  # 您可以根据需要更改分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Automatic requirements.txt for Python Project
      uses: ryan-rozario/pipreqs-action@master
      with:
        PROJECT_PATH: GameCorner  # 您的项目目录
        REQUIREMENT_PATH: ../requirements.txt  # 生成 requirements.txt 的路径
